### ISSUE TITLE
Comparison with DMT method

### ISSUE THREAD

**Issue by rose-jinyang** [YichiZhang98/DTML#4]
Hello
How are you?
Thanks for contributing to this project.
Does this project support 2D segmentation too?
If so, I'm curious if this method outperforms DMT method (https://arxiv.org/pdf/2004.08514.pdf).

**Comment by YichiZhang98** [comment]
Hi, I have not tried our method on 2D segmentation tasks. But it should also work since DTML is a general framework. You can try with 2D backbone networks.

**Comment by liyun-lu** [comment]
您好，方便发布你论文中的预训练模型给我做比较吗？
我是西大的研究生，最近也在做深度学习的医学图像分割，对你的工作非常感兴趣，想要跟你学习，并且用在我的工作上做对比实验。所以希望能得到你的预训练模型，方便复现你们的结果，谢谢啦！
PS. 方便的话可以放个网盘链接吗？

**Comment by YichiZhang98** [comment]
Hi @liyun-lu 
欢迎交流学习，预训练模型已上传至model/
