### ISSUE TITLE
how to get best model

### ISSUE THREAD

**Issue by 18677064404** [YichiZhang98/DTML#5]
Dear Yichi Zhang：

Hi, Thanks for your great work! I am intersted in your work.
 
Sorry to disturb you.I have some qustions. I want to know how to get the best model files :
". /model/DTML_16labels/best_model_dis.pth"     and     ". /model/DTML_16labels/best_model_seg.pth". 
 
Can you tell me how to do it? Thanks

Best wish

**Comment by YichiZhang98** [comment]
Hi, thanks for your interest. 
The trained best model files can be found at https://github.com/YichiZhang98/DTML/tree/main/model/DTML_16labels
Best regards

**Comment by 18677064404** [comment]
Thanks for your reply.Yeah, I see the best model files are already in the model&nbsp;directory.&nbsp;
When I try to adjust parameters to generate a new model directory, I must put the "best_model_*.pth" in model&nbsp;directory&nbsp;first and then run the test_LA.py.
So I want to know how to get the two "best_model_*.pth" files by training. If there need to add code to generate the two files.
Thank you again!


If you are an Chinese, you can read&nbsp;the following:
Yichi Zhang&nbsp;先生您好！
&nbsp; &nbsp; &nbsp; 首先，感谢您的回复。
&nbsp; &nbsp; &nbsp; 是的，我在model文件目录下看到了这两个"best_model_*.pth"&nbsp;文件。但是当我想要调整参数，生成一个新的model文件时，训练完后，需将这两个最佳模型文件放置在这个model文件夹下，才能进行测试。
&nbsp; &nbsp; &nbsp; 我想知道，如何通过训练得到这两个最佳模型文件呢？是不是需要增加代码去生成它呀？
&nbsp; &nbsp; &nbsp; 再次感谢您！






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月6日(星期二) 中午12:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YichiZhang98/DTML] how to get best model (#5)





 
Hi, thanks for your interest.
 The trained best model files can be found at https://github.com/YichiZhang98/DTML/tree/main/model/DTML_16labels
 Best regards

**Comment by YichiZhang98** [comment]
Hi, the trained models are initially generated in "model/LA/DTML_*settings*/". Here, we use the final checkpoint (iter_6000_*.pth) as the best model for testing.

**Comment by 18677064404** [comment]
Hi,Thank you very much. Your reply has helped me a lot!
Wish&nbsp;you&nbsp;the&nbsp;best&nbsp;of&nbsp;luck&nbsp;in&nbsp;your&nbsp;work!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YichiZhang98/DTML"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月7日(星期三) 上午10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YichiZhang98/DTML] how to get best model (#5)





 
Hi, the trained models are initially generated in "model/LA/DTML_settings/". Here, we use the final checkpoint (iter_6000_*.pth) as the best model for testing.

**Comment by 18677064404** [comment]
Hi,I'm sorry for disturbing you again.

I run the file with "iter_6000_seg.pth",  the result showed:average metric is [ 0.18605297  0.10368403 53.06831007 23.19028863]. I try your best model file got the result as your paper showed.

Before running the "test_LA.py", I downloaded the "2018 Atrial Segmentation Challenge COMPLETE DATASET",and then used the "la_heart_processing.py" file to process the "Training Set", and put in in the corresponding directory，and run the file “train_la_dtml” , training success.

So can you give some advice, or is there something I didn't deal with?  Thanks.

**Comment by YichiZhang98** [comment]
Hi, I have not never been in a situation like yours. Maybe you can check if there is something wrong with the training set or testing set. 
Best regards
