### ISSUE TITLE
问您一些小问题，感谢

### ISSUE THREAD

**Issue by xiaozhangya** [YichiZhang98/DTML#6]
作者您好，我今年也中了一篇PRCV2021的文章，想问下您是学生的吗？  现在注册的时候不知道开发票的时候不知道选择那个，想咨询您一下。谢谢。
好不容易找到一个发PRCV的论文，您一定要回复我呀,谢谢！

**Comment by YichiZhang98** [comment]
是的。目前还没有注册，你或许可以联系主办方问一下
